[tasks.build]
command = "wasm-pack"
args = [
  "build",
  "--dev",
  "--target",
  "web",
  "--out-name",
  "wasm",
  "--out-dir",
  "./static",
]
watch = { ignore_pattern = "static/*" }

[tasks.build-ci]
command = "wasm-pack"
args = [
  "build",
  "--release",  # Ensure this is release mode for production
  "--target",
  "web",
  "--out-name",
  "wasm",
  "--out-dir",
  "./static",   # This ensures files go into the ./static directory
]

[tasks.serve]
command = "simple-http-server"
args = [
  "-i",
  "./static/",
  "-p",
  "3000",
  "--nocache",
  "--try-file",
  "./static/index.html",
]
